FROM node:16 as React_build_app
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

FROM nginx
COPY --from=React_build_app /app/build /usr/share/nginx/html