version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Welcome to My Devlopment Mode ProdMode
    ports:
      - "8080:80"
    
    #env_file:
    #   - ./.env

